Add support of resources type in load_dict
mitsuba-renderer/mitsuba3 pull request #744
Opened 2023-05-22 07:36 UTC by Speierers

## Overview

The proposed changes add support for additional external resources folders in the `mi.load_dict()` routine. This is similar to the [existing `resources` tag](https://mitsuba.readthedocs.io/en/stable/src/key_topics/scene_format.html#external-resource-folders) in the XML scene file description.

## Different solutions

### A

Currently, the syntax looks as follow:

```python
mi.load_dict({
    'type': 'scene',
    'foo': { 'type': 'resources', 'path': '../data/textures'},
     ...
})
```

It is a bit redondant to have to define both the `'type'` as `'resources'` and then the `'path'`.  And `'foo'` here is useless.

### B

Another option would be to detect that we have specifying a external resources folder using the LHS key (e.g. here `'foo'`), although this might conflict with other scene objects (e.g. the `path` integrator). Also, with this solution, only a single external folder can be defined.

```python
mi.load_dict({
    'type': 'scene',
    'resources': '../data/textures',
    ...
})
```

### C

As an alternative solution, we could leverage the extra keyword arguments passed to `mi.load_dict()` to specify such paths.

```python
mi.load_dict({
    'type': 'scene',
    ...
}, resources=['../data/textures'])
```

Any thoughts?

2023-05-31 10:51 UTC, dvicini commented
I like solution A because it is the one that is consistent with the XML format. I agree that it is not super elegant, but I think this is fine given that this is a more advanced use case. In my opinion, a more well-structured, consistent syntax is more valuable than a more concise notation

2023-06-09 08:12 UTC, njroussel commented
I would also strongly prefer A for consistency. In addition, it allows user to structure their `dict` such that the path is mentioned right next to whichever plugins need resources from that path.

2023-06-26 08:13 UTC, Speierers commented
Solution A is implemented in this PR. Should we go ahead and merge this?

2023-07-05 09:35 UTC, njroussel requested changes
Looks good to me. 

Before merging, could you add a small example to the documentation too please?

2023-07-06 07:33 UTC, njroussel approved these changes
Thank you :smile:

2023-07-06 07:33 UTC, merged